In [1]:
import pandas as pd
import matplotlib.pyplot as plt

## Data Gathering

In [2]:
data = pd.read_csv('huge_1M_titanic.csv')

## Data Preprocessing

In [3]:
data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1310,1,1,"Name1310, Miss. Surname1310",female,NaN,0,0,SOTON/O2 3101272,76.760165,NaN,C
1,1311,0,3,"Name1311, Col. Surname1311",male,29.0,0,0,223596,10.193097,NaN,S
2,1312,0,3,"Name1312, Mr. Surname1312",male,20.0,0,0,54636,12.029416,C83,C
3,1313,0,3,"Name1313, Mr. Surname1313",male,27.0,0,0,PC 17760,13.429448,NaN,S
4,1314,0,3,"Name1314, Mr. Surname1314",male,32.0,0,0,364512,4.840769,E33,C

In [4]:
data.shape

(1000000, 12)

In [5]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 12 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   PassengerId  1000000 non-null  int64
 1   Survived     1000000 non-null  int64
 2   Pclass       1000000 non-null  int64
 3   Name         1000000 non-null  str
 4   Sex          1000000 non-null  str
 5   Age          801400 non-null   float64
 6   SibSp        1000000 non-null  int64
 7   Parch        1000000 non-null  int64
 8   Ticket       1000000 non-null  str
 9   Fare         1000000 non-null  float64
 10  Cabin        229805 non-null   str
 11  Embarked     997760 non-null   str
dtypes: float64(2), int64(5), str(5)
memory usage: 132.6 MB

In [6]:
data.isnull().sum()

PassengerId         0
Survived            0
Pclass              0
Name                0
Sex                 0
Age            198600
SibSp               0
Parch               0
Ticket              0
Fare                0
Cabin          770195
Embarked         2240
dtype: int64

PassengerId, Name, Ticket , Cabin - not neccessary to keep in the data

In [7]:
data = data.drop(columns=['PassengerId', 'Name', 'Age', 'Cabin', 'Ticket'])

In [8]:
data.head()

   Survived  Pclass     Sex  SibSp  Parch       Fare Embarked
0         1       1  female      0      0  76.760165        C
1         0       3    male      0      0  10.193097        S
2         0       3    male      0      0  12.029416        C
3         0       3    male      0      0  13.429448        S
4         0       3    male      0      0   4.840769        C

In [9]:
data.isnull().sum()

Survived       0
Pclass         0
Sex            0
SibSp          0
Parch          0
Fare           0
Embarked    2240
dtype: int64

In [10]:
data['Embarked'].value_counts()

Embarked
S    729468
C    186846
Q     81446
Name: count, dtype: int64

In [11]:
data['Embarked'].mode()

0    S
Name: Embarked, dtype: str

## Data Cleaning

In [12]:
data['Embarked'] =data['Embarked'].replace({'S':"Southampton", 'C':'Chebourg', 'Q':"Queenstown"})

In [13]:
data.head()

   Survived  Pclass     Sex  SibSp  Parch       Fare     Embarked
0         1       1  female      0      0  76.760165     Chebourg
1         0       3    male      0      0  10.193097  Southampton
2         0       3    male      0      0  12.029416     Chebourg
3         0       3    male      0      0  13.429448  Southampton
4         0       3    male      0      0   4.840769     Chebourg

In [14]:
data.dropna(subset=['Embarked'] , inplace=True)

In [15]:
data.isnull().sum()

Survived    0
Pclass      0
Sex         0
SibSp       0
Parch       0
Fare        0
Embarked    0
dtype: int64

In [16]:
data.shape

(997760, 7)

In [17]:
data['Fare'] = data['Fare'].astype('int8')

In [18]:
data.head()

   Survived  Pclass     Sex  SibSp  Parch  Fare     Embarked
0         1       1  female      0      0    76     Chebourg
1         0       3    male      0      0    10  Southampton
2         0       3    male      0      0    12     Chebourg
3         0       3    male      0      0    13  Southampton
4         0       3    male      0      0     4     Chebourg

Three types of Encoder
1. Label Encoder --> Binary category --> Yes / No
2. Ordinal Encoder --> whenever category will have some order eg [Primary > Secondary > Tertiary]
3. OneHotEncoder --> Create separate columns based on requirement --> give equal priority to all

## Data/Feature Encoding

### Gender --> LabelEncoder

In [19]:
from sklearn.preprocessing import LabelEncoder

In [20]:
label = LabelEncoder()

In [21]:
data['Sex'] = label.fit_transform(data['Sex'])

In [22]:
data.head()

   Survived  Pclass  Sex  SibSp  Parch  Fare     Embarked
0         1       1    0      0      0    76     Chebourg
1         0       3    1      0      0    10  Southampton
2         0       3    1      0      0    12     Chebourg
3         0       3    1      0      0    13  Southampton
4         0       3    1      0      0     4     Chebourg

### OneHotEncoder --> Embarked

In [23]:
from sklearn.preprocessing import OneHotEncoder

In [24]:
onehot = OneHotEncoder(sparse_output=False)

In [25]:
Embarked = onehot.fit_transform(data[['Embarked']])

In [26]:
Embarked = pd.DataFrame(Embarked, columns=onehot.get_feature_names_out())

In [27]:
Embarked

        Embarked_Chebourg  Embarked_Queenstown  Embarked_Southampton
0                     1.0                  0.0                   0.0
1                     0.0                  0.0                   1.0
2                     1.0                  0.0                   0.0
3                     0.0                  0.0                   1.0
4                     1.0                  0.0                   0.0
...                   ...                  ...                   ...
997755                0.0                  0.0                   1.0
997756                0.0                  0.0                   1.0
997757                0.0                  0.0                   1.0
997758                0.0                  0.0                   1.0
997759                0.0                  0.0                   1.0

[997760 rows x 3 columns]

In [28]:
data = pd.concat([data.drop(columns=['Embarked']),Embarked], axis=1)

In [29]:
data.head()

,Survived,Pclass,Sex,SibSp,Parch,Fare,Embarked_Chebourg,Embarked_Queenstown,Embarked_Southampton
0,1.0,1.0,0.0,0.0,0.0,76.0,1.0,0.0,0.0
1,0.0,3.0,1.0,0.0,0.0,10.0,0.0,0.0,1.0
2,0.0,3.0,1.0,0.0,0.0,12.0,1.0,0.0,0.0
3,0.0,3.0,1.0,0.0,0.0,13.0,0.0,0.0,1.0
4,0.0,3.0,1.0,0.0,0.0,4.0,1.0,0.0,0.0

### Feature Scaling

In [30]:
from sklearn.preprocessing import StandardScaler

In [31]:
scale = StandardScaler()

In [32]:
data.columns

Index(['Survived', 'Pclass', 'Sex', 'SibSp', 'Parch', 'Fare',
       'Embarked_Chebourg', 'Embarked_Queenstown', 'Embarked_Southampton'],
      dtype='str')

In [33]:
num_cols = ['Pclass', 'Sex', 'SibSp', 'Parch', 'Fare']

In [34]:
data[num_cols] = scale.fit_transform(data[num_cols])

In [35]:
data.head()

,Survived,Pclass,Sex,SibSp,Parch,Fare,Embarked_Chebourg,Embarked_Queenstown,Embarked_Southampton
0,1.0,-1.568865,-1.359197,-0.462644,-0.469267,1.675922,1.0,0.0,0.0
1,0.0,0.824107,0.735729,-0.462644,-0.469267,-0.234102,0.0,0.0,1.0
2,0.0,0.824107,0.735729,-0.462644,-0.469267,-0.176222,1.0,0.0,0.0
3,0.0,0.824107,0.735729,-0.462644,-0.469267,-0.147283,0.0,0.0,1.0
4,0.0,0.824107,0.735729,-0.462644,-0.469267,-0.407741,1.0,0.0,0.0

In [36]:
import pickle

In [37]:
with open('label_encoder.pkl', 'wb') as file:
    pickle.dump(label, file)

In [38]:
with open('onehot_encoder.pkl', 'wb') as file:
    pickle.dump(onehot, file)

In [39]:
with open('scaler.pkl', 'wb') as file:
    pickle.dump(scale, file)

## Train-Test Split

80% data --> Training ----> 64% training , 16 % validation

20% data --> Testing

In [40]:
X = data.drop(columns='Survived')

In [41]:
y = data['Survived']

In [42]:
X.head()

,Pclass,Sex,SibSp,Parch,Fare,Embarked_Chebourg,Embarked_Queenstown,Embarked_Southampton
0,-1.568865,-1.359197,-0.462644,-0.469267,1.675922,1.0,0.0,0.0
1,0.824107,0.735729,-0.462644,-0.469267,-0.234102,0.0,0.0,1.0
2,0.824107,0.735729,-0.462644,-0.469267,-0.176222,1.0,0.0,0.0
3,0.824107,0.735729,-0.462644,-0.469267,-0.147283,0.0,0.0,1.0
4,0.824107,0.735729,-0.462644,-0.469267,-0.407741,1.0,0.0,0.0

In [43]:
y.head()

0    1.0
1    0.0
2    0.0
3    0.0
4    0.0
Name: Survived, dtype: float64

In [44]:
from sklearn.model_selection import train_test_split

### Train and Testing

In [45]:
X_train, X_test , y_train, y_test = train_test_split(X,y, test_size=20, random_state=42)

### Validation

In [46]:
X_train, X_valid, y_train, y_valid =  train_test_split(X_train, y_train, test_size=0.2, random_state=42)

In [47]:
X_train.shape

(799979, 8)

In [48]:
X_valid.shape

(199995, 8)

## ANN Implementation

- How differ Deep Learning from Machine Learning is Model Training -> ANN Implementation
- DL sequential model -> input -> sequence of layers
- First sequence -> Input layer --> Hidden Layer --> Output Layer
- tensorflow -> sequential
- According to shape, 8 nodes in Input Layer 
- In hidden layer --> much number of nodes --> more complex more thinking compabilities

Input Layer
- 2 node * 3 weight + 3 bias  + 3 node * 3 weight + 3 bias + 1 node * 3 weight + 1 bias  = 25 parameter --> forward + backward propagation

Creating Sequential Model ( ANN Implementation)
- Sequential Network
- Dense -> Hidden Layer --> we can mention the no. of nodes inside the dense layer 
- Activation function - Sigmoid, TanH, ReLu
- Optimizer - AdaGrad, RMSProp, Adam, AdaDelta
- Loss function --> how to reduce
- Metrics --> Accuracy
- TensorBoard --> no. of epochs, how to reduce loss value

In [49]:
import tensorflow

### Model Building Step

In [51]:
(X_train.shape[1],)

(8,)

In [50]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping

In [59]:
model = Sequential([Dense(64, input_shape=(X_train.shape[1],), activation='relu'), # First Hidden Layer
Dense(32, activation='relu'),
Dense(1, activation='sigmoid')
])

c:\Users\arunk\OneDrive\Desktop\Learning\Machine-Learning-Projects\Titanic-Survival-Prediction-1Million-Dataset-Classifier\venv\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [60]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_3 (Dense)                 │ (None, 64)             │           576 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,689 (10.50 KB)

 Trainable params: 2,689 (10.50 KB)

 Non-trainable params: 0 (0.00 B)

### Model Compilation : Optimizer, Loss, Metrics

In [61]:
opt  = tensorflow.keras.optimizers.Adam(learning_rate=0.01)
tensorflow.keras.losses.BinaryFocalCrossentropy

keras.src.losses.losses.BinaryFocalCrossentropy

In [63]:
model.compile(optimizer=opt, loss='binary_crossentropy', metrics=['accuracy'])

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

### Early Stopping Value

In [64]:
stopping_callback = EarlyStopping(monitor='val_loss', patience=5, restore_best_weights=True)

In [65]:
model.fit(X_train, y_train, validation_data=(X_valid, y_valid), epochs=10, callbacks=[stopping_callback])

Epoch 1/10
25000/25000 ━━━━━━━━━━━━━━━━━━━━ 34s 1ms/step - accuracy: 0.6169 - loss: nan - val_accuracy: 0.6176 - val_loss: nan
Epoch 2/10
25000/25000 ━━━━━━━━━━━━━━━━━━━━ 34s 1ms/step - accuracy: 0.6167 - loss: nan - val_accuracy: 0.6176 - val_loss: nan
Epoch 3/10
25000/25000 ━━━━━━━━━━━━━━━━━━━━ 34s 1ms/step - accuracy: 0.6167 - loss: nan - val_accuracy: 0.6176 - val_loss: nan
Epoch 4/10
25000/25000 ━━━━━━━━━━━━━━━━━━━━ 33s 1ms/step - accuracy: 0.6167 - loss: nan - val_accuracy: 0.6176 - val_loss: nan
Epoch 5/10
25000/25000 ━━━━━━━━━━━━━━━━━━━━ 33s 1ms/step - accuracy: 0.6167 - loss: nan - val_accuracy: 0.6176 - val_loss: nan
Epoch 6/10
25000/25000 ━━━━━━━━━━━━━━━━━━━━ 33s 1ms/step - accuracy: 0.6167 - loss: nan - val_accuracy: 0.6176 - val_loss: nan

In [66]:
model.save("model.h5")

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.