In [61]:
import pandas as pd
import matplotlib.pyplot as plt

## Data Gathering

In [62]:
data = pd.read_csv('huge_1M_titanic.csv')

## Data Preprocessing

In [63]:
data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1310,1,1,"Name1310, Miss. Surname1310",female,NaN,0,0,SOTON/O2 3101272,76.760165,NaN,C
1,1311,0,3,"Name1311, Col. Surname1311",male,29.0,0,0,223596,10.193097,NaN,S
2,1312,0,3,"Name1312, Mr. Surname1312",male,20.0,0,0,54636,12.029416,C83,C
3,1313,0,3,"Name1313, Mr. Surname1313",male,27.0,0,0,PC 17760,13.429448,NaN,S
4,1314,0,3,"Name1314, Mr. Surname1314",male,32.0,0,0,364512,4.840769,E33,C

In [64]:
data.shape

(1000000, 12)

In [65]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 12 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   PassengerId  1000000 non-null  int64
 1   Survived     1000000 non-null  int64
 2   Pclass       1000000 non-null  int64
 3   Name         1000000 non-null  str
 4   Sex          1000000 non-null  str
 5   Age          801400 non-null   float64
 6   SibSp        1000000 non-null  int64
 7   Parch        1000000 non-null  int64
 8   Ticket       1000000 non-null  str
 9   Fare         1000000 non-null  float64
 10  Cabin        229805 non-null   str
 11  Embarked     997760 non-null   str
dtypes: float64(2), int64(5), str(5)
memory usage: 132.6 MB

In [66]:
data.isnull().sum()

PassengerId         0
Survived            0
Pclass              0
Name                0
Sex                 0
Age            198600
SibSp               0
Parch               0
Ticket              0
Fare                0
Cabin          770195
Embarked         2240
dtype: int64

PassengerId, Name, Ticket , Cabin - not neccessary to keep in the data

In [67]:
data = data.drop(columns=['PassengerId', 'Name', 'Age', 'Cabin', 'Ticket'])

In [68]:
data.head()

   Survived  Pclass     Sex  SibSp  Parch       Fare Embarked
0         1       1  female      0      0  76.760165        C
1         0       3    male      0      0  10.193097        S
2         0       3    male      0      0  12.029416        C
3         0       3    male      0      0  13.429448        S
4         0       3    male      0      0   4.840769        C

In [69]:
data.isnull().sum()

Survived       0
Pclass         0
Sex            0
SibSp          0
Parch          0
Fare           0
Embarked    2240
dtype: int64

In [70]:
data['Embarked'].value_counts()

Embarked
S    729468
C    186846
Q     81446
Name: count, dtype: int64

In [71]:
data['Embarked'].mode()

0    S
Name: Embarked, dtype: str

## Data Cleaning

In [72]:
data['Embarked'] =data['Embarked'].replace({'S':"Southampton", 'C':'Chebourg', 'Q':"Queenstown"})

In [73]:
data.head()

   Survived  Pclass     Sex  SibSp  Parch       Fare     Embarked
0         1       1  female      0      0  76.760165     Chebourg
1         0       3    male      0      0  10.193097  Southampton
2         0       3    male      0      0  12.029416     Chebourg
3         0       3    male      0      0  13.429448  Southampton
4         0       3    male      0      0   4.840769     Chebourg

In [74]:
data.dropna(subset=['Embarked'] , inplace=True)

In [75]:
data.isnull().sum()

Survived    0
Pclass      0
Sex         0
SibSp       0
Parch       0
Fare        0
Embarked    0
dtype: int64

In [76]:
data.shape

(997760, 7)

In [77]:
data['Fare'] = data['Fare'].astype('int8')

In [78]:
data.head()

   Survived  Pclass     Sex  SibSp  Parch  Fare     Embarked
0         1       1  female      0      0    76     Chebourg
1         0       3    male      0      0    10  Southampton
2         0       3    male      0      0    12     Chebourg
3         0       3    male      0      0    13  Southampton
4         0       3    male      0      0     4     Chebourg

Three types of Encoder
1. Label Encoder --> Binary category --> Yes / No
2. Ordinal Encoder --> whenever category will have some order eg [Primary > Secondary > Tertiary]
3. OneHotEncoder --> Create separate columns based on requirement --> give equal priority to all

## Data/Feature Encoding

### Gender --> LabelEncoder

In [79]:
from sklearn.preprocessing import LabelEncoder

In [80]:
label = LabelEncoder()

In [81]:
data['Sex'] = label.fit_transform(data['Sex'])

In [82]:
data.head()

   Survived  Pclass  Sex  SibSp  Parch  Fare     Embarked
0         1       1    0      0      0    76     Chebourg
1         0       3    1      0      0    10  Southampton
2         0       3    1      0      0    12     Chebourg
3         0       3    1      0      0    13  Southampton
4         0       3    1      0      0     4     Chebourg

### OneHotEncoder --> Embarked

In [83]:
from sklearn.preprocessing import OneHotEncoder

In [84]:
onehot = OneHotEncoder(sparse_output=False)

In [85]:
Embarked = onehot.fit_transform(data[['Embarked']])

In [86]:
Embarked = pd.DataFrame(Embarked, columns=onehot.get_feature_names_out())

In [87]:
Embarked

        Embarked_Chebourg  Embarked_Queenstown  Embarked_Southampton
0                     1.0                  0.0                   0.0
1                     0.0                  0.0                   1.0
2                     1.0                  0.0                   0.0
3                     0.0                  0.0                   1.0
4                     1.0                  0.0                   0.0
...                   ...                  ...                   ...
997755                0.0                  0.0                   1.0
997756                0.0                  0.0                   1.0
997757                0.0                  0.0                   1.0
997758                0.0                  0.0                   1.0
997759                0.0                  0.0                   1.0

[997760 rows x 3 columns]

In [88]:
data = pd.concat([data.drop(columns=['Embarked']),Embarked], axis=1)

In [89]:
data.head()

,Survived,Pclass,Sex,SibSp,Parch,Fare,Embarked_Chebourg,Embarked_Queenstown,Embarked_Southampton
0,1.0,1.0,0.0,0.0,0.0,76.0,1.0,0.0,0.0
1,0.0,3.0,1.0,0.0,0.0,10.0,0.0,0.0,1.0
2,0.0,3.0,1.0,0.0,0.0,12.0,1.0,0.0,0.0
3,0.0,3.0,1.0,0.0,0.0,13.0,0.0,0.0,1.0
4,0.0,3.0,1.0,0.0,0.0,4.0,1.0,0.0,0.0

### Feature Scaling

In [90]:
from sklearn.preprocessing import StandardScaler

In [91]:
scale = StandardScaler()

In [92]:
data.columns

Index(['Survived', 'Pclass', 'Sex', 'SibSp', 'Parch', 'Fare',
       'Embarked_Chebourg', 'Embarked_Queenstown', 'Embarked_Southampton'],
      dtype='str')

In [95]:
num_cols = ['Pclass', 'Sex', 'SibSp', 'Parch', 'Fare']

In [96]:
data[num_cols] = scale.fit_transform(data[num_cols])

In [97]:
data.head()

,Survived,Pclass,Sex,SibSp,Parch,Fare,Embarked_Chebourg,Embarked_Queenstown,Embarked_Southampton
0,1.0,-1.568865,-1.359197,-0.462644,-0.469267,1.675922,1.0,0.0,0.0
1,0.0,0.824107,0.735729,-0.462644,-0.469267,-0.234102,0.0,0.0,1.0
2,0.0,0.824107,0.735729,-0.462644,-0.469267,-0.176222,1.0,0.0,0.0
3,0.0,0.824107,0.735729,-0.462644,-0.469267,-0.147283,0.0,0.0,1.0
4,0.0,0.824107,0.735729,-0.462644,-0.469267,-0.407741,1.0,0.0,0.0

In [98]:
import pickle

In [99]:
with open('label_encoder.pkl', 'wb') as file:
    pickle.dump(label, file)

In [100]:
with open('onehot_encoder.pkl', 'wb') as file:
    pickle.dump(onehot, file)

In [101]:
with open('scaler.pkl', 'wb') as file:
    pickle.dump(scale, file)

## Train-Test Split

80% data --> Training ----> 64% training , 16 % validation

20% data --> Testing

In [102]:
X = data.drop(columns='Survived')

In [103]:
y = data['Survived']

In [104]:
X.head()

,Pclass,Sex,SibSp,Parch,Fare,Embarked_Chebourg,Embarked_Queenstown,Embarked_Southampton
0,-1.568865,-1.359197,-0.462644,-0.469267,1.675922,1.0,0.0,0.0
1,0.824107,0.735729,-0.462644,-0.469267,-0.234102,0.0,0.0,1.0
2,0.824107,0.735729,-0.462644,-0.469267,-0.176222,1.0,0.0,0.0
3,0.824107,0.735729,-0.462644,-0.469267,-0.147283,0.0,0.0,1.0
4,0.824107,0.735729,-0.462644,-0.469267,-0.407741,1.0,0.0,0.0

In [105]:
y.head()

0    1.0
1    0.0
2    0.0
3    0.0
4    0.0
Name: Survived, dtype: float64

In [106]:
from sklearn.model_selection import train_test_split

### Train and Testing

In [107]:
X_train, X_test , y_train, y_test = train_test_split(X,y, test_size=20, random_state=42)

### Validation

In [108]:
X_train, X_valid, y_train, y_valid =  train_test_split(X_train, y_train, test_size=0.2, random_state=42)

In [109]:
X_train.shape

(799979, 8)

In [111]:
X_valid.shape

(199995, 8)