## Prediction using ANN Model

In [1]:
from tensorflow.keras.models import load_model
import pickle
import pandas as pd
import tensorflow as tf

In [2]:
with open("../label_encoder.pkl", 'rb') as file:
    label = pickle.load(file)

In [3]:
with open("../onehot_encoder.pkl", 'rb') as file:
    onehot = pickle.load(file)

In [4]:
with open("../scaler.pkl", 'rb') as file:
    scaler = pickle.load(file)

In [5]:
model = load_model('../model.h5')

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

WARNING:absl:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

In [6]:
user={'Pclass':3,'Sex': 'female', 'SibSp':1, 'Parch':1, 'Fare':11, 'Embarked': 'Queenstown'}

In [7]:
user={'Pclass':1,'Sex': 'male', 'SibSp':1, 'Parch':1, 'Fare':11, 'Embarked': 'Queenstown'}

In [8]:
user={'Pclass':1,'Sex': 'female', 'SibSp':1, 'Parch':1, 'Fare':11, 'Embarked': 'Chebourg'}

In [9]:
user = pd.DataFrame([user])

In [10]:
user

   Pclass     Sex  SibSp  Parch  Fare  Embarked
0       1  female      1      1    11  Chebourg

In [11]:
user['Sex'] = label.transform(user['Sex'])

In [12]:
user

   Pclass  Sex  SibSp  Parch  Fare  Embarked
0       1    0      1      1    11  Chebourg

In [13]:
embarked = onehot.transform(user[['Embarked']])

In [14]:
embarked = pd.DataFrame(embarked, columns=onehot.get_feature_names_out())

In [15]:
embarked

   Embarked_Chebourg  Embarked_Queenstown  Embarked_Southampton
0                1.0                  0.0                   0.0

In [16]:
user = pd.concat([user.drop(columns=['Embarked']), embarked],axis=1)

In [17]:
user

,Pclass,Sex,SibSp,Parch,Fare,Embarked_Chebourg,Embarked_Queenstown,Embarked_Southampton
0,1,0,1,1,11,1.0,0.0,0.0

In [18]:
user[['Pclass', 'SibSp', 'Parch', 'Fare']] = scaler.transform(user[['Pclass', 'SibSp', 'Parch', 'Fare']])

In [19]:
user

,Pclass,Sex,SibSp,Parch,Fare,Embarked_Chebourg,Embarked_Queenstown,Embarked_Southampton
0,-1.568865,0,0.442462,0.833802,-0.205162,1.0,0.0,0.0

In [20]:
y = model.predict(user)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step

In [21]:
y = y[0][0]

In [22]:
y

np.float32(0.99998856)

In [23]:
if y > 0.5:
    print("The Passenger will likely Survived in the Titanic Journey")
else:
    print("The Passenger won't Survived")

The Passenger will likely Survived in the Titanic Journey