In [135]:
import pandas as pd
import matplotlib.pyplot as plt

## Data Gathering

In [136]:
data = pd.read_csv('../dataset/huge_1M_titanic.csv')

In [137]:
# data = data.sample(10000)

## Data Preprocessing

In [138]:
data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1310,1,1,"Name1310, Miss. Surname1310",female,NaN,0,0,SOTON/O2 3101272,76.760165,NaN,C
1,1311,0,3,"Name1311, Col. Surname1311",male,29.0,0,0,223596,10.193097,NaN,S
2,1312,0,3,"Name1312, Mr. Surname1312",male,20.0,0,0,54636,12.029416,C83,C
3,1313,0,3,"Name1313, Mr. Surname1313",male,27.0,0,0,PC 17760,13.429448,NaN,S
4,1314,0,3,"Name1314, Mr. Surname1314",male,32.0,0,0,364512,4.840769,E33,C

In [139]:
data.shape

(1000000, 12)

In [140]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 12 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   PassengerId  1000000 non-null  int64
 1   Survived     1000000 non-null  int64
 2   Pclass       1000000 non-null  int64
 3   Name         1000000 non-null  str
 4   Sex          1000000 non-null  str
 5   Age          801400 non-null   float64
 6   SibSp        1000000 non-null  int64
 7   Parch        1000000 non-null  int64
 8   Ticket       1000000 non-null  str
 9   Fare         1000000 non-null  float64
 10  Cabin        229805 non-null   str
 11  Embarked     997760 non-null   str
dtypes: float64(2), int64(5), str(5)
memory usage: 132.6 MB

In [141]:
data.isnull().sum()

PassengerId         0
Survived            0
Pclass              0
Name                0
Sex                 0
Age            198600
SibSp               0
Parch               0
Ticket              0
Fare                0
Cabin          770195
Embarked         2240
dtype: int64

PassengerId, Name, Ticket , Cabin - not neccessary to keep in the data

In [142]:
data = data.drop(columns=['PassengerId', 'Name', 'Age', 'Cabin', 'Ticket'])

In [143]:
data.head()

   Survived  Pclass     Sex  SibSp  Parch       Fare Embarked
0         1       1  female      0      0  76.760165        C
1         0       3    male      0      0  10.193097        S
2         0       3    male      0      0  12.029416        C
3         0       3    male      0      0  13.429448        S
4         0       3    male      0      0   4.840769        C

In [144]:
data.isnull().sum()

Survived       0
Pclass         0
Sex            0
SibSp          0
Parch          0
Fare           0
Embarked    2240
dtype: int64

In [145]:
data['Embarked'].value_counts()

Embarked
S    729468
C    186846
Q     81446
Name: count, dtype: int64

In [146]:
data['Embarked'].mode()

0    S
Name: Embarked, dtype: str

## Data Cleaning

In [147]:
data['Embarked'] =data['Embarked'].replace({'S':"Southampton", 'C':'Chebourg', 'Q':"Queenstown"})

In [148]:
data.head()

   Survived  Pclass     Sex  SibSp  Parch       Fare     Embarked
0         1       1  female      0      0  76.760165     Chebourg
1         0       3    male      0      0  10.193097  Southampton
2         0       3    male      0      0  12.029416     Chebourg
3         0       3    male      0      0  13.429448  Southampton
4         0       3    male      0      0   4.840769     Chebourg

In [149]:
data.dropna(subset=['Embarked'] , inplace=True)

In [150]:
data.isnull().sum()

Survived    0
Pclass      0
Sex         0
SibSp       0
Parch       0
Fare        0
Embarked    0
dtype: int64

In [151]:
data.shape

(997760, 7)

In [152]:
data['Fare'] = data['Fare'].astype('int8')

In [153]:
data.head()

   Survived  Pclass     Sex  SibSp  Parch  Fare     Embarked
0         1       1  female      0      0    76     Chebourg
1         0       3    male      0      0    10  Southampton
2         0       3    male      0      0    12     Chebourg
3         0       3    male      0      0    13  Southampton
4         0       3    male      0      0     4     Chebourg

Three types of Encoder
1. Label Encoder --> Binary category --> Yes / No
2. Ordinal Encoder --> whenever category will have some order eg [Primary > Secondary > Tertiary]
3. OneHotEncoder --> Create separate columns based on requirement --> give equal priority to all

## Data/Feature Encoding

### Gender --> LabelEncoder

In [154]:
from sklearn.preprocessing import LabelEncoder

In [155]:
label = LabelEncoder()

In [156]:
data['Sex'] = label.fit_transform(data['Sex'])

In [157]:
data.head()

   Survived  Pclass  Sex  SibSp  Parch  Fare     Embarked
0         1       1    0      0      0    76     Chebourg
1         0       3    1      0      0    10  Southampton
2         0       3    1      0      0    12     Chebourg
3         0       3    1      0      0    13  Southampton
4         0       3    1      0      0     4     Chebourg

### OneHotEncoder --> Embarked

In [158]:
from sklearn.preprocessing import OneHotEncoder

In [159]:
onehot = OneHotEncoder(sparse_output=False)

In [160]:
Embarked = onehot.fit_transform(data[['Embarked']])

In [161]:
Embarked = pd.DataFrame(Embarked, columns=onehot.get_feature_names_out())

In [162]:
Embarked

        Embarked_Chebourg  Embarked_Queenstown  Embarked_Southampton
0                     1.0                  0.0                   0.0
1                     0.0                  0.0                   1.0
2                     1.0                  0.0                   0.0
3                     0.0                  0.0                   1.0
4                     1.0                  0.0                   0.0
...                   ...                  ...                   ...
997755                0.0                  0.0                   1.0
997756                0.0                  0.0                   1.0
997757                0.0                  0.0                   1.0
997758                0.0                  0.0                   1.0
997759                0.0                  0.0                   1.0

[997760 rows x 3 columns]

In [163]:
data = pd.concat([data.drop(columns=['Embarked']),Embarked], axis=1)

In [164]:
data.head()

,Survived,Pclass,Sex,SibSp,Parch,Fare,Embarked_Chebourg,Embarked_Queenstown,Embarked_Southampton
0,1.0,1.0,0.0,0.0,0.0,76.0,1.0,0.0,0.0
1,0.0,3.0,1.0,0.0,0.0,10.0,0.0,0.0,1.0
2,0.0,3.0,1.0,0.0,0.0,12.0,1.0,0.0,0.0
3,0.0,3.0,1.0,0.0,0.0,13.0,0.0,0.0,1.0
4,0.0,3.0,1.0,0.0,0.0,4.0,1.0,0.0,0.0

### Feature Scaling

In [165]:
from sklearn.preprocessing import StandardScaler

In [166]:
scale = StandardScaler()

In [167]:
data.columns

Index(['Survived', 'Pclass', 'Sex', 'SibSp', 'Parch', 'Fare',
       'Embarked_Chebourg', 'Embarked_Queenstown', 'Embarked_Southampton'],
      dtype='str')

In [168]:
# num_cols = ['Pclass', 'Sex', 'SibSp', 'Parch', 'Fare']

In [169]:
num_cols = ['Pclass',  'SibSp', 'Parch', 'Fare']

In [170]:
data[num_cols] = scale.fit_transform(data[num_cols])

In [171]:
data.head()

,Survived,Pclass,Sex,SibSp,Parch,Fare,Embarked_Chebourg,Embarked_Queenstown,Embarked_Southampton
0,1.0,-1.568865,0.0,-0.462644,-0.469267,1.675922,1.0,0.0,0.0
1,0.0,0.824107,1.0,-0.462644,-0.469267,-0.234102,0.0,0.0,1.0
2,0.0,0.824107,1.0,-0.462644,-0.469267,-0.176222,1.0,0.0,0.0
3,0.0,0.824107,1.0,-0.462644,-0.469267,-0.147283,0.0,0.0,1.0
4,0.0,0.824107,1.0,-0.462644,-0.469267,-0.407741,1.0,0.0,0.0

In [172]:
import pickle

In [173]:
with open('../label_encoder.pkl', 'wb') as file:
    pickle.dump(label, file)

In [174]:
with open('../onehot_encoder.pkl', 'wb') as file:
    pickle.dump(onehot, file)

In [175]:
with open('../scaler.pkl', 'wb') as file:
    pickle.dump(scale, file)

## Train-Test Split

80% data --> Training ----> 64% training , 16 % validation

20% data --> Testing

In [176]:
data.head()

,Survived,Pclass,Sex,SibSp,Parch,Fare,Embarked_Chebourg,Embarked_Queenstown,Embarked_Southampton
0,1.0,-1.568865,0.0,-0.462644,-0.469267,1.675922,1.0,0.0,0.0
1,0.0,0.824107,1.0,-0.462644,-0.469267,-0.234102,0.0,0.0,1.0
2,0.0,0.824107,1.0,-0.462644,-0.469267,-0.176222,1.0,0.0,0.0
3,0.0,0.824107,1.0,-0.462644,-0.469267,-0.147283,0.0,0.0,1.0
4,0.0,0.824107,1.0,-0.462644,-0.469267,-0.407741,1.0,0.0,0.0

In [177]:
data.isnull().sum()

Survived                2234
Pclass                  2234
Sex                     2234
SibSp                   2234
Parch                   2234
Fare                    2234
Embarked_Chebourg       2234
Embarked_Queenstown     2234
Embarked_Southampton    2234
dtype: int64

In [178]:
data = data.dropna()

In [179]:
data.isnull().sum()

Survived                0
Pclass                  0
Sex                     0
SibSp                   0
Parch                   0
Fare                    0
Embarked_Chebourg       0
Embarked_Queenstown     0
Embarked_Southampton    0
dtype: int64

In [180]:
X = data.drop(columns='Survived')

In [181]:
y = data['Survived']

In [182]:
X.head()

,Pclass,Sex,SibSp,Parch,Fare,Embarked_Chebourg,Embarked_Queenstown,Embarked_Southampton
0,-1.568865,0.0,-0.462644,-0.469267,1.675922,1.0,0.0,0.0
1,0.824107,1.0,-0.462644,-0.469267,-0.234102,0.0,0.0,1.0
2,0.824107,1.0,-0.462644,-0.469267,-0.176222,1.0,0.0,0.0
3,0.824107,1.0,-0.462644,-0.469267,-0.147283,0.0,0.0,1.0
4,0.824107,1.0,-0.462644,-0.469267,-0.407741,1.0,0.0,0.0

In [183]:
y.head()

0    1.0
1    0.0
2    0.0
3    0.0
4    0.0
Name: Survived, dtype: float64

In [184]:
X.isnull().sum()

Pclass                  0
Sex                     0
SibSp                   0
Parch                   0
Fare                    0
Embarked_Chebourg       0
Embarked_Queenstown     0
Embarked_Southampton    0
dtype: int64

In [185]:
y.isnull().sum()

np.int64(0)

In [186]:
from sklearn.model_selection import train_test_split

### Train and Testing

In [187]:
X_train, X_test , y_train, y_test = train_test_split(X,y, test_size=20, random_state=42)

### Validation

In [188]:
X_train, X_valid, y_train, y_valid =  train_test_split(X_train, y_train, test_size=0.2, random_state=42)

In [189]:
X_train.shape

(796404, 8)

In [190]:
X_valid.shape

(199102, 8)

In [191]:
X_train.isnull().sum()

Pclass                  0
Sex                     0
SibSp                   0
Parch                   0
Fare                    0
Embarked_Chebourg       0
Embarked_Queenstown     0
Embarked_Southampton    0
dtype: int64

## ANN Implementation

- How differ Deep Learning from Machine Learning is Model Training -> ANN Implementation
- DL sequential model -> input -> sequence of layers
- First sequence -> Input layer --> Hidden Layer --> Output Layer
- tensorflow -> sequential
- According to shape, 8 nodes in Input Layer 
- In hidden layer --> much number of nodes --> more complex more thinking compabilities

Input Layer
- 2 node * 3 weight + 3 bias  + 3 node * 3 weight + 3 bias + 1 node * 3 weight + 1 bias  = 25 parameter --> forward + backward propagation

Creating Sequential Model ( ANN Implementation)
- Sequential Network
- Dense -> Hidden Layer --> we can mention the no. of nodes inside the dense layer 
- Activation function - Sigmoid, TanH, ReLu
- Optimizer - AdaGrad, RMSProp, Adam, AdaDelta
- Loss function --> how to reduce
- Metrics --> Accuracy
- TensorBoard --> no. of epochs, how to reduce loss value

In [192]:
import tensorflow

### Model Building Step

In [193]:
(X_train.shape[1],)

(8,)

In [194]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping

In [195]:
# model = Sequential([Dense(64, input_shape=(X_train.shape[1],), activation='relu'), # First Hidden Layer
# Dense(32, activation='relu'),
# Dense(1, activation='sigmoid')
# ])

In [196]:
model = Sequential([Dense(128, input_shape=(X_train.shape[1],), activation='relu'), # First Hidden Layer
Dense(64, activation='relu'),
Dense(32, activation='relu'),
Dense(1, activation='sigmoid')
])

c:\Users\arunk\OneDrive\Desktop\Learning\Machine-Learning-Projects\Titanic-Survival-Prediction-1Million-Dataset-Classifier\venv\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [197]:
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_8 (Dense)                 │ (None, 128)            │         1,152 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_9 (Dense)                 │ (None, 64)             │         8,256 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_10 (Dense)                │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_11 (Dense)                │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 11,521 (45.00 KB)

 Trainable params: 11,521 (45.00 KB)

 Non-trainable params: 0 (0.00 B)

### Model Compilation : Optimizer, Loss, Metrics

In [198]:
opt  = tensorflow.keras.optimizers.Adam(learning_rate=0.01)

In [199]:
model.compile(optimizer=opt, loss='binary_crossentropy', metrics=['accuracy'])

### Early Stopping Value

In [200]:
stopping_callback = EarlyStopping(monitor='val_loss', patience=5, restore_best_weights=True)

In [201]:
model.fit(X_train, y_train, validation_data=(X_valid, y_valid), epochs=10, callbacks=[stopping_callback])

Epoch 1/10
24888/24888 ━━━━━━━━━━━━━━━━━━━━ 33s 1ms/step - accuracy: 0.8447 - loss: 0.3494 - val_accuracy: 0.8501 - val_loss: 0.3399
Epoch 2/10
24888/24888 ━━━━━━━━━━━━━━━━━━━━ 32s 1ms/step - accuracy: 0.8501 - loss: 0.3384 - val_accuracy: 0.8529 - val_loss: 0.3326
Epoch 3/10
24888/24888 ━━━━━━━━━━━━━━━━━━━━ 32s 1ms/step - accuracy: 0.8511 - loss: 0.3362 - val_accuracy: 0.8545 - val_loss: 0.3363
Epoch 4/10
24888/24888 ━━━━━━━━━━━━━━━━━━━━ 32s 1ms/step - accuracy: 0.8515 - loss: 0.3362 - val_accuracy: 0.8550 - val_loss: 0.3342
Epoch 5/10
24888/24888 ━━━━━━━━━━━━━━━━━━━━ 33s 1ms/step - accuracy: 0.8524 - loss: 0.3353 - val_accuracy: 0.8552 - val_loss: 0.3289
Epoch 6/10
24888/24888 ━━━━━━━━━━━━━━━━━━━━ 32s 1ms/step - accuracy: 0.8520 - loss: 0.3352 - val_accuracy: 0.8536 - val_loss: 0.3367
Epoch 7/10
24888/24888 ━━━━━━━━━━━━━━━━━━━━ 33s 1ms/step - accuracy: 0.8522 - loss: 0.3343 - val_accuracy: 0.8530 - val_loss: 0.3292
Epoch 8/10
24888/24888 ━━━━━━━━━━━━━━━━━━━━ 32s 1ms/step - accuracy: 0.8522 - loss: 0.3345 - val_accuracy: 0.8549 - val_loss: 0.3310
Epoch 9/10
24888/24888 ━━━━━━━━━━━━━━━━━━━━ 32s 1ms/step - accuracy: 0.8518 - loss: 0.3348 - val_accuracy: 0.8529 - val_loss: 0.3347
Epoch 10/10
24888/24888 ━━━━━━━━━━━━━━━━━━━━ 33s 1ms/step - accuracy: 0.8525 - loss: 0.3346 - val_accuracy: 0.8548 - val_loss: 0.3343

In [202]:
model.save("../model.h5")

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.